version: '3'

services:
  controller:
    build:
      context: ./fedora
      dockerfile: Dockerfile
      image: localhost/fedora
    image: localhost/fedora
    container_name: controller
    hostname: controller
    networks:
      - mynetwork

  ubuntu:
    build:
      context: ./ubuntu
      dockerfile: Dockerfile
      image: localhost/ubuntu
    image: localhost/ubuntu
    container_name: ubuntu
    hostname: ubuntu
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1