---
- name: Manage Apache Web Server
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Install the Apache Web Server Package
      package:
        name: httpd
        state: present
    - name: add web content
      copy:
        src: www/
        dest: /var/www/html/
    - name: Start and enable Apache web server
      service:
        name: httpd
        state: started
        enabled: true